import { describe, expect, it } from 'vitest';
import { GitmodulesParseError, parseGitmodules } from './gitmodules.js';

describe('parseGitmodules — canonical form', () => {
  it('parses a single submodule section', () => {
    const content = `[submodule "vendor/foo"]\n\tpath = vendor/foo\n\turl = https://example.com/foo.git\n`;

    expect(parseGitmodules(content)).toEqual([{ name: 'vendor/foo', path: 'vendor/foo' }]);
  });

  it('parses multiple submodule sections in order of first appearance', () => {
    const content = ['[submodule "a"]', 'path = libs/a', '[submodule "b"]', 'path = libs/b'].join(
      '\n',
    );

    expect(parseGitmodules(content)).toEqual([
      { name: 'a', path: 'libs/a' },
      { name: 'b', path: 'libs/b' },
    ]);
  });
});

describe('parseGitmodules — real-world git-config forms, not only the canonical one', () => {
  it('accepts a full-line comment introduced by "#"', () => {
    const content = ['# generated by git submodule add', '[submodule "a"]', 'path = a'].join('\n');

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'a' }]);
  });

  it('accepts a full-line comment introduced by ";"', () => {
    const content = ['; legacy comment style', '[submodule "a"]', 'path = a'].join('\n');

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'a' }]);
  });

  it('cuts off an inline "#" comment after the value', () => {
    const content = ['[submodule "a"]', 'path = a # pinned to v2'].join('\n');

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'a' }]);
  });

  it('cuts off an inline ";" comment after the value', () => {
    const content = ['[submodule "a"]', 'path = a ; pinned to v2'].join('\n');

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'a' }]);
  });

  it('ignores whitespace variation around "="', () => {
    const content = ['[submodule "a"]', 'path=a', '[submodule "b"]', 'path\t=\tb'].join('\n');

    expect(parseGitmodules(content)).toEqual([
      { name: 'a', path: 'a' },
      { name: 'b', path: 'b' },
    ]);
  });

  it('accepts an escaped quote inside a quoted subsection name', () => {
    const content = String.raw`[submodule "vendor \"pinned\""]` + '\npath = vendor/pinned';

    expect(parseGitmodules(content)).toEqual([{ name: 'vendor "pinned"', path: 'vendor/pinned' }]);
  });

  it('accepts a subsection name containing a dot and a space', () => {
    const content = '[submodule "libs/vendor.io project"]\npath = libs/vendor';

    expect(parseGitmodules(content)).toEqual([
      { name: 'libs/vendor.io project', path: 'libs/vendor' },
    ]);
  });

  it('matches the "path" key case-insensitively', () => {
    const content = ['[submodule "a"]', 'Path = a'].join('\n');

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'a' }]);

    const contentUpper = ['[submodule "b"]', 'PATH = b'].join('\n');
    expect(parseGitmodules(contentUpper)).toEqual([{ name: 'b', path: 'b' }]);
  });

  it('ignores an unrelated section in the same file (e.g. [core])', () => {
    const content = ['[core]', 'repositoryformatversion = 0', '[submodule "a"]', 'path = a'].join(
      '\n',
    );

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'a' }]);
  });

  it('handles CRLF line endings', () => {
    const content = '[submodule "a"]\r\npath = a\r\n[submodule "b"]\r\npath = b\r\n';

    expect(parseGitmodules(content)).toEqual([
      { name: 'a', path: 'a' },
      { name: 'b', path: 'b' },
    ]);
  });

  it('joins a backslash line continuation before parsing the value', () => {
    const content = '[submodule "a"]\npath = libs/\\\nfoo';

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'libs/foo' }]);
  });

  it('a later "path" in the same section overrides an earlier one', () => {
    const content = ['[submodule "a"]', 'path = old/a', 'path = new/a'].join('\n');

    expect(parseGitmodules(content)).toEqual([{ name: 'a', path: 'new/a' }]);
  });
});

describe('parseGitmodules — edge cases', () => {
  it('returns an empty list for an empty file', () => {
    expect(parseGitmodules('')).toEqual([]);
  });

  it('ignores a submodule section with no "path" key', () => {
    const content = ['[submodule "a"]', 'url = https://example.com/a.git'].join('\n');

    expect(parseGitmodules(content)).toEqual([]);
  });

  it('throws for an unterminated quoted subsection name', () => {
    expect(() => {
      parseGitmodules('[submodule "unterminated\npath = a');
    }).toThrow(GitmodulesParseError);
  });

  it('throws for an unterminated quoted value', () => {
    const content = ['[submodule "a"]', 'path = "unterminated'].join('\n');

    expect(() => {
      parseGitmodules(content);
    }).toThrow(GitmodulesParseError);
  });

  it('throws for a malformed section header', () => {
    expect(() => {
      parseGitmodules('[submodule "a"\npath = a');
    }).toThrow(GitmodulesParseError);
  });
});
